kind: pipeline
name: test

steps:
- name: flake8
  image: python:3.7
  commands:
  - pip install flake8 > /dev/null
  - flake8
---

kind: pipeline
name: build qemu image

steps:
- name: build qemu image
  image: mgax/vmck:build-copy-file
  privileged: true
  volumes:
  - name: vmck-images
    path: /vmck-images
  commands:
  - tar czf /tmp/cluster.tar.gz .
  - /opt/vmck/contrib/build.py /vmck-images/cluster-master.qcow2.tmp --script /drone/src/ci/provision-vm.sh --copy-file /tmp/cluster.tar.gz:/opt/cluster.tar.gz
  - mv /vmck-images/cluster-master.qcow2.tmp /vmck-images/cluster-master.qcow2

depends_on:
- test

trigger:
  status:
  - success
  branch:
  - master
  event:
  - push

volumes:
- name: vmck-images
  host:
      path: /opt/volumes/vmck-images
