kind: pipeline
name: test-syntax

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

---
kind: pipeline
name: publish to docker hub

trigger:
  status:
  - success
  event:
  - push
  - tag
  - cron

depends_on:
- test-syntax

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    force_tag: true
    repo: liquidinvestigations/cluster
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - cron
  depends_on:
    - clone

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    force_tag: true
    repo: liquidinvestigations/cluster
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  depends_on:
    - clone


---
kind: pipeline
name: integration-tests

depends_on:
- publish to docker hub

concurrency:
  limit: 1

node:
  connect_target_ssh: true

steps:
- name: copy code to target
  image: appleboy/drone-scp:latest
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    source: .
    target: /app-test/code
    rm: true


- name: run tests on target
  image: appleboy/drone-ssh:latest
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    command_timeout: 60m
    script:
      - cd /app-test/code
      - ./ci/run-integration-tests.sh

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password

---
kind: secret
name: target_username
get:
  path: liquid/ci/drone.target
  name: username

---
kind: secret
name: target_password
get:
  path: liquid/ci/drone.target
  name: password

---
kind: secret
name: target_hostname
get:
  path: liquid/ci/drone.target
  name: hostname

---
kind: secret
name: target_port
get:
  path: liquid/ci/drone.target
  name: port
