kind: pipeline
name: test

steps:
- name: flake8
  image: python:3.6
  commands:
  - pip install flake8 > /dev/null
  - flake8

- name: test
  image: docker:dind
  privileged: true
  commands:
  - apk add --update libcap bash curl wget git python3 py3-pip  > /dev/null
  - pip3 install -q pipenv supervisor
  - pipenv install --system --deploy --ignore-pipfile
  - ./examples/network.sh
  - ./cluster.py install
  - setcap cap_ipc_lock=+ep bin/vault
  - ls -al bin
  - ./bin/nomad --version
  - dockerd &
  - sleep 5; until docker version; do sleep 5; done
  - cp examples/cluster.ini .
  - ./cluster.py supervisord &
  - sleep 20
  - ./cluster.py supervisorctl -- tail -f nomad &
  - ./cluster.py wait
---

kind: pipeline
name: build qemu image

steps:
- name: build qemu image
  image: vmck/vmck:0.0.1
  privileged: true
  volumes:
  - name: vmck-images
    path: /vmck-images
  commands:
  - BRANCH=$(echo $DRONE_COMMIT_BRANCH | tr -s '/' '_')
  - tar czf /tmp/cluster.tar.gz .
  - /opt/vmck/contrib/build.py /tmp/cluster-$BRANCH.qcow2 --script /drone/src/ci/provision-vm.sh --copy-file /tmp/cluster.tar.gz:/opt/cluster.tar.gz
  - tar czvf /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz -C /tmp cluster-$BRANCH.qcow2
  - mv /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz /vmck-images/cluster-$BRANCH.qcow2.tar.gz

depends_on:
- test

trigger:
  status:
  - success
  branch:
  - master
  - build-image/*
  event:
  - push

volumes:
- name: vmck-images
  host:
      path: /opt/volumes/vmck-images

---
kind: pipeline
name: publish to docker hub

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/cluster
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/cluster
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
