kind: pipeline
name: test

concurrency:
  limit: 3

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

- name: test on host
  image: vmck/vagrant-vmck:0.4.1
  depends_on:
  - flake8
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export PROVISION=/opt/cluster/ci/test-host.sh
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER-$DRONE_STEP_NAME"
  - git clean -fdX
  - ./ci/run-vagrant-test.sh


---
kind: pipeline
name: build qemu image

concurrency:
  limit: 1

steps:
- name: build qemu image
  image: vmck/vmck:0.5
  privileged: true
  volumes:
  - name: vmck-images
    path: /vmck-images
  commands:
  - BRANCH=$(echo $DRONE_COMMIT_BRANCH | tr -s '/' '_')
  - tar czf /tmp/cluster.tar.gz .
  - ./ci/build-image.py /tmp/cluster-$BRANCH.qcow2 --script /drone/src/ci/provision-vm.sh --copy-file /tmp/cluster.tar.gz:/opt/cluster.tar.gz
  - tar czvf /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz -C /tmp cluster-$BRANCH.qcow2
  - mv /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz /vmck-images/cluster-$BRANCH.qcow2.tar.gz

depends_on:
- test

trigger:
  status:
  - success
  branch:
  - master
  - build-image/*
  event:
  - push
  - cron

volumes:
- name: vmck-images
  host:
      path: /opt/volumes/vmck-images

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password

