kind: pipeline
name: test-syntax

steps:
- name: flake8
  image: alpine/flake8:6.0.0
  commands:
  - flake8

---
kind: pipeline
name: publish to docker hub

trigger:
  status:
  - success
  event:
  - push
  - tag
  - cron

depends_on:
- test-syntax

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: liquidinvestigations/drone-docker-buildx:2023-09-25
  privileged: true
  settings:
    force_tag: true
    repo: liquidinvestigations/cluster
    tags: ${DRONE_COMMIT_BRANCH}
    platforms:
      - linux/amd64
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - cron
  depends_on:
    - clone

- name: docker push autotag + latest
  image: liquidinvestigations/drone-docker-buildx:2023-09-25
  privileged: true
  settings:
    force_tag: true
    repo: liquidinvestigations/cluster
    auto_tag: true
    platforms:
      - linux/amd64
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  depends_on:
    - clone

      # ---
      # kind: pipeline
      # name: test-vms
      # 
      # depends_on:
      # - publish to docker hub
      # 
      # concurrency:
      #   limit: 1
      # 
      # steps:
      # - name: test on host
      #   image: vmck/vagrant-vmck:0.4.1
      #   depends_on:
      #   - clone
      #   commands:
      #   - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
      #   - export PROVISION=/opt/cluster/ci/test-host.sh
      #   - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER-$DRONE_STEP_NAME"
      #   - git clean -fdX
      #   - ./ci/run-vagrant-test.sh
      # 
      # - name: test docker container
      #   image: vmck/vagrant-vmck:0.4.1
      #   depends_on:
      #   - clone
      #   commands:
      #   - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
      #   - export PROVISION=/opt/cluster/ci/test-docker.sh
      #   - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER-$DRONE_STEP_NAME"
      #   - git clean -fdX
      #   - ./ci/run-vagrant-test.sh
      # 
      # - name: cluster 3 containers
      #   image: vmck/vagrant-vmck:0.4.1
      #   depends_on:
      #   - clone
      #   commands:
      #   - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
      #   - export PROVISION=/opt/cluster/ci/test-triple.sh
      #   - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER-$DRONE_STEP_NAME"
      #   - export VMCK_MEMORY=6000
      #   - git clean -fdX
      #   - ./ci/run-vagrant-test.sh

    # ---
    # kind: pipeline
    # name: build qemu image
    # 
    # node:
    #   liquid_volumes: /opt/volumes
    # 
    # steps:
    # - name: build qemu image
    #   image: vmck/vmck:0.5
    #   privileged: true
    #   volumes:
    #   - name: vmck-images
    #     path: /vmck-images
    #   commands:
    #   - BRANCH=$(echo $DRONE_COMMIT_BRANCH | tr -s '/' '_')
    #   - tar czf /tmp/cluster.tar.gz .
    #   - ./ci/build-image.py /tmp/cluster-$BRANCH.qcow2 --script /drone/src/ci/provision-vm.sh --copy-file /tmp/cluster.tar.gz:/opt/cluster.tar.gz
    #   - tar czvf /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz -C /tmp cluster-$BRANCH.qcow2
    #   - mv /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz /vmck-images/cluster-$BRANCH.qcow2.tar.gz
    # 
    # depends_on:
    # - publish to docker hub
    # 
    # concurrency:
    #   limit: 1
    # 
    # trigger:
    #   status:
    #   - success
    #   branch:
    #   - master
    #   - build-image/*
    #   event:
    #   - push
    #   - cron
    # 
    # volumes:
    # - name: vmck-images
    #   host:
    #       path: /opt/volumes/vmck-images

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password

