kind: pipeline
name: test

steps:
- name: flake8
  image: python:3.7
  commands:
  - pip install flake8 > /dev/null
  - flake8

- name: docker build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5; until docker version; do sleep 5; done
  - docker build . --tag liquidinvestigations/cluster

- name: run servers and autovault
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - apk update && apk add bash curl sed
  - cp examples/cluster.ini .
  - sed -i -- 's/liquid-bridge/lo/g' cluster.ini
  - sed -i -- 's/10.66.60.1/127.0.0.1/g' cluster.ini
  - cat cluster.ini
  - ./examples/docker.sh
  - docker exec cluster /bin/sh -exc 'until supervisorctl status; do sleep 3; done'
  - docker exec cluster supervisorctl tail autovault
  - docker exec cluster supervisorctl tail cluster:nomad
  - docker exec cluster supervisorctl tail cluster:consul
  - docker exec cluster supervisorctl tail cluster:vault
  - docker exec cluster python cluster.py autovault

services:
- name: docker daemon in docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
---

kind: pipeline
name: build qemu image

steps:
- name: build qemu image
  image: mgax/vmck:build-copy-file
  privileged: true
  volumes:
  - name: vmck-images
    path: /vmck-images
  commands:
  - tar czf /tmp/cluster.tar.gz .
  - /opt/vmck/contrib/build.py /vmck-images/cluster-master.qcow2.tmp --script /drone/src/ci/provision-vm.sh --copy-file /tmp/cluster.tar.gz:/opt/cluster.tar.gz
  - mv /vmck-images/cluster-master.qcow2.tmp /vmck-images/cluster-master.qcow2

depends_on:
- test

trigger:
  status:
  - success
  branch:
  - master
  event:
  - push

volumes:
- name: vmck-images
  host:
      path: /opt/volumes/vmck-images
