kind: pipeline
name: test

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

- name: test on host
  image: vmck/vagrant-vmck:0.4.1
  depends_on:
  - flake8
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export PROVISION=/opt/cluster/ci/test-host.sh
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER-$DRONE_STEP_NAME"
  - ./ci/run-vagrant-test.sh

- name: test docker container
  image: vmck/vagrant-vmck:0.4.1
  depends_on:
  - flake8
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export PROVISION=/opt/cluster/ci/test-docker.sh
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER-$DRONE_STEP_NAME"
  - ./ci/run-vagrant-test.sh

#- name: cluster 3 containers
#  image: vmck/vagrant-vmck
#  depends_on:
#  - test on host
#  - test docker container
#  commands:
#  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
#  - export PROVISION=/opt/cluster/ci/test-triple.sh
#  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER-$DRONE_STEP_NAME"
#  - export VMCK_MEMORY=6000
#  - ./ci/run-vagrant-test.sh

---
kind: pipeline
name: publish to docker hub

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/cluster
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/cluster
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: build qemu image

steps:
- name: build qemu image
  image: vmck/vmck:0.5
  privileged: true
  volumes:
  - name: vmck-images
    path: /vmck-images
  commands:
  - BRANCH=$(echo $DRONE_COMMIT_BRANCH | tr -s '/' '_')
  - tar czf /tmp/cluster.tar.gz .
  - /opt/vmck/contrib/build.py /tmp/cluster-$BRANCH.qcow2 --script /drone/src/ci/provision-vm.sh --copy-file /tmp/cluster.tar.gz:/opt/cluster.tar.gz
  - tar czvf /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz -C /tmp cluster-$BRANCH.qcow2
  - mv /vmck-images/cluster-$BRANCH-tmp.qcow2.tar.gz /vmck-images/cluster-$BRANCH.qcow2.tar.gz

depends_on:
- publish to docker hub

trigger:
  status:
  - success
  branch:
  - master
  - build-image/*
  event:
  - push
  - cron

volumes:
- name: vmck-images
  host:
      path: /opt/volumes/vmck-images

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password

