#!/bin/bash -e

if [ "$EUID" -ne 0 ]; then
    set -x
    echo "Please run as root"
    exit 1
fi


cd "$( dirname "${BASH_SOURCE[0]}" )"

if [[ ! -f cluster.ini ]]; then
    set -x
    echo "Please write cluster.ini"
    exit 1
fi

export PIPENV_VENV_IN_PROJECT=1

exec pipenv run ./cluster.py "$@"
