apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc-sentry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: "3Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc-grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: "3Gi"
