# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'etc'

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-env")
    config.env.enable
  end

  config.vm.box = "base"
  config.vm.define ENV['VMNAME']

  # disable implicit mount for /vagrant
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "..", "/opt/cluster", type: "rsync",
      rsync__exclude: [".vagrant/", ".git/", "__pycache__/"],
      rsync_args: ["--verbose", "--ignore-from", "../.gitignore",
                   "--archive", "--delete", "-z", "--copy-links"]


  config.vm.provision "shell", inline: "( set +ex; " + ENV['PROVISION'] + ") 2>&1",
      privileged: false

  config.vm.box = "base"
  config.nfs.functional = false

  config.vm.provider :vmck do |vmck, override|
    vmck.vmck_url = ENV['VMCK_URL']
    vmck.image_path = "imgbuild-master.qcow2.tar.gz"
    vmck.memory = 4000
    vmck.cpus = 1
  end
end
